// `switchboard shortcut` — generates a one-click Windows launcher for
// WSL-based setups (the project's target environment, PRD section 1): a .lnk
// on the user's Windows Desktop (or Startup folder with --startup) that runs
// `switchboard up` inside WSL and opens the dashboard in the Windows browser.
//
// Why this shape:
// - The engine is a .bat calling `wsl.exe -d <distro> -- bash -lc "node
//   '<bin shim>' up"`: a LOGIN shell (-l) loads ~/.profile so the user's PATH
//   (node managers, ~/.local/bin where tmux may live) is complete, and the
//   absolute bin-shim path makes the shortcut independent of `npm link`.
// - What the user CLICKS is a .lnk pointing at that .bat, because a .bat cannot
//   carry an icon — Windows always paints it with the generic gear — while a
//   .lnk has an IconLocation. The .lnk also runs minimized (WindowStyle 7), so
//   the console does not flash in the user's face on every boot.
// - Both the .bat and the .ico live in %LOCALAPPDATA%\Switchboard, not on the
//   Desktop: the Desktop should hold ONE clickable thing, and the icon must sit
//   on real NTFS. A \\wsl$\... IconLocation renders blank whenever the distro is
//   not running — which is exactly the case at boot, when the Startup shortcut
//   is drawn.
// - The dashboard is reachable from Windows at http://127.0.0.1:<port>/
//   thanks to WSL2's built-in localhost forwarding — the hub itself still
//   binds 127.0.0.1 INSIDE WSL only (D6 intact; forwarding is Windows-local).
// - The Windows folders are resolved via PowerShell's
//   [Environment]::GetFolderPath, which honors OneDrive-redirected folders.

import fs from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";
import { loadConfig } from "../server/config.js";
import { CliError, runCliAction, type OutFn } from "./common.js";

const execFileAsync = promisify(execFile);

/** Repo-root bin shim, resolved relative to this module (works from any cwd). */
function binShimPath(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../bin/switchboard.mjs");
}

/** Repo-root icon (generated by scripts/make-icon.mjs), same resolution rule. */
function iconSourcePath(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../assets/switchboard.ico");
}

/**
 * Escapes a string for a PowerShell SINGLE-quoted literal (only ' needs
 * doubling there). Every value we interpolate is machine-derived — a folder
 * path from GetFolderPath — but "C:\Users\Tim O'Brien\Desktop" is an ordinary
 * Windows path, and unescaped it would end the literal and run the tail.
 */
function psQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * The PowerShell that creates the .lnk (pure — unit-tested). WScript.Shell is
 * the COM object every Windows ships; there is no dependency to add here.
 * WindowStyle 7 = minimized.
 */
export function shortcutLnkScript(input: {
  lnkPath: string; // Windows path (C:\...)
  targetPath: string; // the .bat, Windows path
  iconPath: string; // the .ico, Windows path
}): string {
  return [
    `$s = (New-Object -ComObject WScript.Shell).CreateShortcut(${psQuote(input.lnkPath)})`,
    `$s.TargetPath = ${psQuote(input.targetPath)}`,
    `$s.WorkingDirectory = ${psQuote(path.win32.dirname(input.targetPath))}`,
    `$s.IconLocation = ${psQuote(input.iconPath)}`,
    "$s.WindowStyle = 7",
    `$s.Description = ${psQuote("Start the Switchboard hub (WSL) and open the dashboard")}`,
    "$s.Save()",
  ].join("; ");
}

/**
 * The .bat content (pure — unit-tested). ASCII-only and CRLF (cmd.exe is
 * unreliable with bare LF), closes by itself on success and pauses on failure
 * so the user can read the error.
 *
 * nodePath is ABSOLUTE and captured at generation time (process.execPath):
 * `wsl.exe -- bash -lc` starts a NON-INTERACTIVE login shell whose PATH comes
 * only from ~/.profile — version managers (n, nvm) usually add their bin dir
 * in ~/.bashrc BELOW the interactivity guard, so a bare `node` is NOT found
 * there (real user report: the Desktop shortcut failed with
 * "node: command not found" while the same line worked from an interactive
 * shell, which inherits the full PATH).
 */
export function shortcutBatContent(input: {
  distro: string;
  shimPath: string;
  nodePath: string;
  port: number;
}): string {
  const lines = [
    "@echo off",
    "title Switchboard",
    "echo Starting the Switchboard hub (WSL)...",
    // Single quotes around the paths survive bash -lc; both come from this
    // machine's own install (no user input) but may contain spaces.
    `wsl.exe -d ${input.distro} -- bash -lc "'${input.nodePath}' '${input.shimPath}' up"`,
    "if errorlevel 1 (",
    "  echo.",
    "  echo The hub could not start. Read the message above.",
    "  pause",
    "  exit /b 1",
    ")",
    // 127.0.0.1, NOT localhost. The hub binds 127.0.0.1 — that is a security
    // invariant, not a default — while "localhost" resolves to ::1 first on a
    // modern Windows/WSL box. The browser then knocks on an IPv6 address where
    // nothing is listening and the dashboard hangs on "connecting" forever,
    // with every agent alive and unreachable behind it. Verified here:
    // http://[::1]:4577 → ECONNREFUSED, http://127.0.0.1:4577 → OK.
    `start "" http://127.0.0.1:${input.port}/`,
  ];
  return lines.join("\r\n") + "\r\n";
}

/**
 * GetFolderPath names. "LocalApplicationData" is %LOCALAPPDATA% — where the
 * .bat and the .ico live (see the file header).
 */
export type WindowsFolder = "Desktop" | "Startup" | "LocalApplicationData";

/**
 * Resolves a Windows special folder from inside WSL: PowerShell gives the
 * REAL folder (OneDrive-aware), wslpath converts it to a /mnt/... path.
 */
async function windowsFolderAsWslPath(folder: WindowsFolder): Promise<string> {
  const { stdout: winPath } = await execFileAsync("powershell.exe", [
    "-NoProfile",
    "-Command",
    `[Environment]::GetFolderPath('${folder}')`,
  ]);
  const trimmed = winPath.replace(/\r?\n/g, "").trim();
  if (trimmed === "") {
    throw new CliError(`Could not resolve the Windows ${folder} folder via PowerShell.`);
  }
  const { stdout: wsl } = await execFileAsync("wslpath", ["-u", trimmed]);
  return wsl.replace(/\r?\n/g, "").trim();
}

/** /mnt/c/... → C:\... (the .lnk fields only take Windows paths). */
async function wslPathToWindows(wslPath: string): Promise<string> {
  const { stdout } = await execFileAsync("wslpath", ["-w", wslPath]);
  const win = stdout.replace(/\r?\n/g, "").trim();
  if (win === "") throw new CliError(`Could not convert "${wslPath}" to a Windows path.`);
  return win;
}

async function execPowerShell(script: string): Promise<void> {
  await execFileAsync("powershell.exe", ["-NoProfile", "-Command", script]);
}

export interface ShortcutOptions {
  /** Install into the Windows Startup folder (runs on boot) instead of the Desktop. */
  startup?: boolean;
  // -- injectables (index.ts uses the defaults; tests override) --------------
  baseDir?: string;
  out?: OutFn;
  distro?: string;
  shimPath?: string;
  /** Absolute node binary embedded in the .bat (default: process.execPath). */
  nodePath?: string;
  iconPath?: string;
  resolveFolder?: (folder: WindowsFolder) => Promise<string>;
  writeFile?: (filePath: string, content: string) => void;
  mkdir?: (dir: string) => void;
  copyFile?: (from: string, to: string) => void;
  /** Converts a /mnt/... path to its C:\... form (default: wslpath -w). */
  toWindowsPath?: (wslPath: string) => Promise<string>;
  /** Runs the .lnk-creating PowerShell (default: powershell.exe -NoProfile -Command). */
  runPowerShell?: (script: string) => Promise<void>;
  /** Reads a file for the "is this stale .bat ours?" check (default: fs). */
  readFileIfExists?: (filePath: string) => string | null;
  removeFile?: (filePath: string) => void;
}

export async function runShortcut(options: ShortcutOptions = {}): Promise<void> {
  const out = options.out ?? console.log;

  // WSL only: on plain Linux/macOS there is no Windows side to put a shortcut
  // on — auto-start (start/wire/up) already covers those.
  const distro = options.distro ?? process.env.WSL_DISTRO_NAME;
  if (!distro) {
    throw new CliError(
      "switchboard shortcut is for Windows + WSL setups (it creates a Windows .bat that boots " +
        "the hub inside WSL). This session does not look like WSL (WSL_DISTRO_NAME is not set). " +
        'On Linux/macOS just rely on the auto-start: any "switchboard up/start/wire" boots the hub.',
    );
  }

  const resolveFolder = options.resolveFolder ?? windowsFolderAsWslPath;
  const writeFile = options.writeFile ?? ((p: string, c: string) => fs.writeFileSync(p, c));
  const mkdir = options.mkdir ?? ((d: string) => fs.mkdirSync(d, { recursive: true }));
  const copyFile = options.copyFile ?? ((f: string, t: string) => fs.copyFileSync(f, t));
  const toWindowsPath = options.toWindowsPath ?? wslPathToWindows;
  const runPowerShell = options.runPowerShell ?? execPowerShell;
  const readFileIfExists =
    options.readFileIfExists ??
    ((p: string) => (fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null));
  const removeFile = options.removeFile ?? ((p: string) => fs.unlinkSync(p));

  // The engine (.bat) and the icon go to %LOCALAPPDATA%\Switchboard; only the
  // .lnk lands where the user looks. See the file header.
  const appDir = path.join(await resolveFolder("LocalApplicationData"), "Switchboard");
  mkdir(appDir);

  const batPath = path.join(appDir, "Switchboard.bat");
  writeFile(
    batPath,
    shortcutBatContent({
      distro,
      shimPath: options.shimPath ?? binShimPath(),
      nodePath: options.nodePath ?? process.execPath,
      port: loadConfig(options.baseDir).port,
    }),
  );

  const iconPath = path.join(appDir, "switchboard.ico");
  copyFile(options.iconPath ?? iconSourcePath(), iconPath);

  const folder: WindowsFolder = options.startup ? "Startup" : "Desktop";
  const dir = await resolveFolder(folder);
  const lnkPath = path.join(dir, "Switchboard.lnk");
  await runPowerShell(
    shortcutLnkScript({
      lnkPath: await toWindowsPath(lnkPath),
      targetPath: await toWindowsPath(batPath),
      iconPath: await toWindowsPath(iconPath),
    }),
  );

  // Earlier versions put the .bat itself here. Leaving it behind means two
  // Switchboard things on the Desktop, one of them iconless — so it goes, but
  // ONLY after confirming it is one of ours. Anything else with that name is
  // the user's file and is left alone (and said out loud).
  const stale = path.join(dir, "Switchboard.bat");
  const staleContent = readFileIfExists(stale);
  if (staleContent !== null) {
    if (staleContent.includes("wsl.exe -d") && staleContent.includes("title Switchboard")) {
      removeFile(stale);
      out(`Removed the old iconless launcher: ${stale}`);
    } else {
      out(`Left ${stale} alone — it is not a launcher this tool wrote.`);
    }
  }

  out(`Shortcut created: ${lnkPath}`);
  if (options.startup) {
    out(
      "It lives in the Windows STARTUP folder: on every boot the hub comes up in the " +
        "background and the dashboard opens. Delete the file to undo.",
    );
  } else {
    out(
      "Double-click it on the Desktop to bring the hub up and open the dashboard. " +
        'Tip: "switchboard shortcut --startup" also installs it to run on Windows boot.',
    );
  }
}

export function registerShortcutCommand(program: Command): void {
  program
    .command("shortcut")
    .description(
      "Creates a one-click Windows launcher (Switchboard.bat) on the Desktop — or in the " +
        "Startup folder with --startup, so the hub comes up on every boot. WSL setups only.",
    )
    .option("--startup", "install into the Windows Startup folder (runs on boot)")
    .action(async (opts: { startup?: boolean }) => {
      await runCliAction(() => runShortcut({ startup: opts.startup }));
    });
}
