// Shared data models for Switchboard.
// Source of truth: PRD-switchboard.md — sections 7 (config), 8 (data models)
// and 10.1 (SSE events). Keep these types in sync with the PRD.

export type AgentStatus = "online" | "offline";

export interface Agent {
  name: string; // ^[a-z0-9][a-z0-9-]{1,30}$ , unique
  role: string; // free-form description, e.g. "backend da API de pagamentos"
  tmuxSession: string; // e.g. "sb-alpha" (prefix + name)
  cwd: string; // directory where claude was opened
  status: AgentStatus; // derived from tmux has-session during polling
  mcpConnected: boolean; // true after the first join via MCP
  muted: boolean; // dashboard can silence nudges (messages are still recorded)
  createdAt: string; // ISO 8601
  lastSeenAt: string; // last MCP interaction or last positive polling
  lastNudgeAt: string | null;
  /**
   * Capability token (PRD v1.1 addendum, sections 9.1/10.1/15): generated by
   * the store on register (and REGENERATED on re-attach), delivered to the
   * agent's session via the SWITCHBOARD_AGENT_TOKEN env var, required by the
   * MCP join to claim this name. Persisted in agents.json (local trust
   * model). Optional for compatibility with pre-v1.1 snapshots — a missing
   * token means "legacy record": the first join claims it and generates one.
   */
  token?: string;
}

/**
 * Public view of an Agent — everything that LEAVES the hub (GET /api/agents,
 * SSE payloads, MCP tool outputs, dashboard, logs) uses this shape. The
 * capability token NEVER appears here; it is only handed out by the register
 * response and by the on-the-fly / legacy-claim join (PRD 9.1/10.1 v1.1).
 */
export type PublicAgent = Omit<Agent, "token">;

/**
 * Redaction helper — the single way to turn a live Agent into its public
 * view. Every hub exit point (REST, SSE, MCP tools) must go through it.
 * Returns a copy; the live store object is never mutated.
 */
export function toPublicAgent(agent: Agent): PublicAgent {
  const { token: _token, ...publicView } = agent;
  return publicView;
}

export interface Message {
  id: string; // ULID
  from: string; // agent name | "operator"
  to: string; // agent name | "all"
  body: string; // plain text, <= maxMessageBytes
  createdAt: string; // ISO 8601
  readAt: string | null; // filled when check_messages delivers
  // For to === "all": the message is expanded into N records, one per recipient,
  // sharing the same broadcastId for tracking. The expansion is done by the
  // caller (hub/MCP layer), NOT by the store.
  broadcastId: string | null;
}

// ---------------------------------------------------------------------------
// Delivery outcome of a stored message (PRD section 9.2 — output of the
// send_message tool). Produced by the Phase 3 nudge dispatcher wired into the
// hub's onMessage extension point: "nudged" (tmux nudge fired), "coalesced"
// (cooldown active, joined the pending set), "queued_offline" (tmux session
// not alive) or "queued_muted" (recipient muted on the dashboard).
// ---------------------------------------------------------------------------

export type Delivery = "nudged" | "coalesced" | "queued_offline" | "queued_muted";

/**
 * Extension point wired in hub.ts: called once per stored message (AFTER the
 * JSONL append — storage is the source of truth, delivery is best-effort)
 * with the recipient's live Agent record. Returns the delivery outcome.
 * Phase 3 implements this with the tmux nudge dispatcher; it must NEVER
 * block (every MCP tool answers in < 1s — PRD section 4, rule 4).
 */
export type OnMessage = (message: Message, recipient: Agent) => Delivery;

// ---------------------------------------------------------------------------
// Configuration (PRD section 7). Every key has a default; the config file
// (~/.switchboard/config.json) may not exist at all.
// ---------------------------------------------------------------------------

export type LogLevel = "debug" | "info" | "warn" | "error";

export interface Config {
  port: number; // default 4577
  tmuxSessionPrefix: string; // default "sb-"
  nudgeCooldownMs: number; // default 15000
  nudgeEnterDelayMs: number; // default 500
  pairRateLimitPerMinute: number; // default 12
  maxMessageBytes: number; // default 16384
  kickoffDelayMs: number; // default 8000
  agentPollIntervalMs: number; // default 10000
  logLevel: LogLevel; // default "info"
}

// ---------------------------------------------------------------------------
// SSE events streamed on GET /api/events (PRD section 10.1).
// {type: agent_updated|message_created|message_read|nudge_sent, payload}
// ---------------------------------------------------------------------------

export interface AgentUpdatedEvent {
  type: "agent_updated";
  // PublicAgent, not Agent: SSE reaches the dashboard (and any local curl) —
  // the capability token must never ride an event (PRD v1.1 addendum).
  payload: PublicAgent;
}

export interface MessageCreatedEvent {
  type: "message_created";
  payload: Message;
}

export interface MessageReadEvent {
  type: "message_read";
  // Mirrors the JSONL read event appended by the store.
  payload: { messageId: string; readAt: string };
}

export interface NudgeSentEvent {
  type: "nudge_sent";
  payload: { agent: string; at: string; unread: number };
}

export type SseEvent =
  | AgentUpdatedEvent
  | MessageCreatedEvent
  | MessageReadEvent
  | NudgeSentEvent;
